#!/bin/bash

runtime=$1

numactl -m 0 fio --iodepth=128 --direct=1 --ioengine=libaio --sync=0 --time_based --runtime=$runtime --cpus_allowed=1 --thread --cpus_allowed_policy=split --group_reporting --ramp_time=5 --allow_mounted_write=1 --size=32G --numjobs=8 --name=xx --bs=128k --rw=read --filename=/dev/nvme0n1 --output-format=json --output=/home/jason/data/ml/storage_io/Storage/_result/row_2.json &
numactl -m 0 fio --iodepth=128 --direct=1 --ioengine=libaio --sync=0 --time_based --runtime=$runtime --cpus_allowed=2 --thread --cpus_allowed_policy=split --group_reporting --ramp_time=5 --allow_mounted_write=1 --size=32G --numjobs=8 --name=xx --bs=128k --rw=read --filename=/dev/nvme1n1 --output-format=json --output=/home/jason/data/ml/storage_io/Storage/_result/row_3.json &
numactl -m 0 fio --iodepth=128 --direct=1 --ioengine=libaio --sync=0 --time_based --runtime=$runtime --cpus_allowed=3 --thread --cpus_allowed_policy=split --group_reporting --ramp_time=5 --allow_mounted_write=1 --size=32G --numjobs=8 --name=xx --bs=128k --rw=read --filename=/dev/nvme2n1 --output-format=json --output=/home/jason/data/ml/storage_io/Storage/_result/row_4.json &
numactl -m 0 fio --iodepth=128 --direct=1 --ioengine=libaio --sync=0 --time_based --runtime=$runtime --cpus_allowed=4 --thread --cpus_allowed_policy=split --group_reporting --ramp_time=5 --allow_mounted_write=1 --size=32G --numjobs=8 --name=xx --bs=128k --rw=read --filename=/dev/nvme3n1 --output-format=json --output=/home/jason/data/ml/storage_io/Storage/_result/row_5.json &
numactl -m 0 fio --iodepth=128 --direct=1 --ioengine=libaio --sync=0 --time_based --runtime=$runtime --cpus_allowed=5 --thread --cpus_allowed_policy=split --group_reporting --ramp_time=5 --allow_mounted_write=1 --size=32G --numjobs=8 --name=xx --bs=128k --rw=read --filename=/dev/nvme4n1 --output-format=json --output=/home/jason/data/ml/storage_io/Storage/_result/row_6.json &
numactl -m 0 fio --iodepth=128 --direct=1 --ioengine=libaio --sync=0 --time_based --runtime=$runtime --cpus_allowed=6 --thread --cpus_allowed_policy=split --group_reporting --ramp_time=5 --allow_mounted_write=1 --size=32G --numjobs=8 --name=xx --bs=128k --rw=read --filename=/dev/nvme5n1 --output-format=json --output=/home/jason/data/ml/storage_io/Storage/_result/row_7.json &
numactl -m 0 fio --iodepth=128 --direct=1 --ioengine=libaio --sync=0 --time_based --runtime=$runtime --cpus_allowed=7 --thread --cpus_allowed_policy=split --group_reporting --ramp_time=5 --allow_mounted_write=1 --size=32G --numjobs=8 --name=xx --bs=128k --rw=read --filename=/dev/nvme6n1 --output-format=json --output=/home/jason/data/ml/storage_io/Storage/_result/row_8.json &
numactl -m 0 fio --iodepth=128 --direct=1 --ioengine=libaio --sync=0 --time_based --runtime=$runtime --cpus_allowed=8 --thread --cpus_allowed_policy=split --group_reporting --ramp_time=5 --allow_mounted_write=1 --size=32G --numjobs=8 --name=xx --bs=128k --rw=read --filename=/dev/nvme7n1 --output-format=json --output=/home/jason/data/ml/storage_io/Storage/_result/row_9.json &
numactl -m 0 fio --iodepth=128 --direct=1 --ioengine=libaio --sync=0 --time_based --runtime=$runtime --cpus_allowed=9 --thread --cpus_allowed_policy=split --group_reporting --ramp_time=5 --allow_mounted_write=1 --size=32G --numjobs=8 --name=xx --bs=128k --rw=read --filename=/dev/nvme8n1 --output-format=json --output=/home/jason/data/ml/storage_io/Storage/_result/row_10.json &
numactl -m 0 fio --iodepth=128 --direct=1 --ioengine=libaio --sync=0 --time_based --runtime=$runtime --cpus_allowed=10 --thread --cpus_allowed_policy=split --group_reporting --ramp_time=5 --allow_mounted_write=1 --size=32G --numjobs=8 --name=xx --bs=128k --rw=read --filename=/dev/nvme9n1 --output-format=json --output=/home/jason/data/ml/storage_io/Storage/_result/row_11.json &
numactl -m 0 fio --iodepth=128 --direct=1 --ioengine=libaio --sync=0 --time_based --runtime=$runtime --cpus_allowed=11 --thread --cpus_allowed_policy=split --group_reporting --ramp_time=5 --allow_mounted_write=1 --size=32G --numjobs=8 --name=xx --bs=128k --rw=read --filename=/dev/nvme10n1 --output-format=json --output=/home/jason/data/ml/storage_io/Storage/_result/row_12.json &
numactl -m 0 fio --iodepth=128 --direct=1 --ioengine=libaio --sync=0 --time_based --runtime=$runtime --cpus_allowed=12 --thread --cpus_allowed_policy=split --group_reporting --ramp_time=5 --allow_mounted_write=1 --size=32G --numjobs=8 --name=xx --bs=128k --rw=read --filename=/dev/nvme11n1 --output-format=json --output=/home/jason/data/ml/storage_io/Storage/_result/row_13.json &
numactl -m 0 fio --iodepth=128 --direct=1 --ioengine=libaio --sync=0 --time_based --runtime=$runtime --cpus_allowed=13 --thread --cpus_allowed_policy=split --group_reporting --ramp_time=5 --allow_mounted_write=1 --size=32G --numjobs=8 --name=xx --bs=128k --rw=read --filename=/dev/nvme12n1 --output-format=json --output=/home/jason/data/ml/storage_io/Storage/_result/row_14.json &
numactl -m 0 fio --iodepth=128 --direct=1 --ioengine=libaio --sync=0 --time_based --runtime=$runtime --cpus_allowed=14 --thread --cpus_allowed_policy=split --group_reporting --ramp_time=5 --allow_mounted_write=1 --size=32G --numjobs=8 --name=xx --bs=128k --rw=read --filename=/dev/nvme13n1 --output-format=json --output=/home/jason/data/ml/storage_io/Storage/_result/row_15.json &
numactl -m 0 fio --iodepth=128 --direct=1 --ioengine=libaio --sync=0 --time_based --runtime=$runtime --cpus_allowed=15 --thread --cpus_allowed_policy=split --group_reporting --ramp_time=5 --allow_mounted_write=1 --size=32G --numjobs=8 --name=xx --bs=128k --rw=read --filename=/dev/nvme14n1 --output-format=json --output=/home/jason/data/ml/storage_io/Storage/_result/row_16.json &
numactl -m 0 fio --iodepth=128 --direct=1 --ioengine=libaio --sync=0 --time_based --runtime=$runtime --cpus_allowed=16 --thread --cpus_allowed_policy=split --group_reporting --ramp_time=5 --allow_mounted_write=1 --size=32G --numjobs=8 --name=xx --bs=128k --rw=read --filename=/dev/nvme15n1 --output-format=json --output=/home/jason/data/ml/storage_io/Storage/_result/row_17.jsonn &
