#!/bin/bash
rtime=$1
bz=$2
export SPDK_FILE_NAME="trtype=PCIe  traddr=0000.06.00.0 ns=1 " ; LD_PRELOAD=./spdk/build/fio/spdk_nvme  fio/fio ./spdk.fio --iodepth=256         --direct=1 --ioengine=spdk --thread=1         --time_based --runtime=$rtime         --ramp_time=5         --cpus_allowed=6         --group_reporting         	  --bs=$bz --rw=read    --output-format=json --output=/home/jason/data/ml/storage_io/Storage/_result/row_2.json &
export SPDK_FILE_NAME="trtype=PCIe  traddr=0000.07.00.0 ns=1 " ; LD_PRELOAD=./spdk/build/fio/spdk_nvme  fio/fio ./spdk.fio --iodepth=256         --direct=1 --ioengine=spdk --thread=1         --time_based --runtime=$rtime         --ramp_time=5         --cpus_allowed=7         --group_reporting         	  --bs=$bz --rw=read    --output-format=json --output=/home/jason/data/ml/storage_io/Storage/_result/row_3.json &
export SPDK_FILE_NAME="trtype=PCIe  traddr=0000.08.00.0 ns=1 " ; LD_PRELOAD=./spdk/build/fio/spdk_nvme  fio/fio ./spdk.fio --iodepth=256         --direct=1 --ioengine=spdk --thread=1         --time_based --runtime=$rtime         --ramp_time=5         --cpus_allowed=8         --group_reporting         	  --bs=$bz --rw=read    --output-format=json --output=/home/jason/data/ml/storage_io/Storage/_result/row_4.json &
export SPDK_FILE_NAME="trtype=PCIe  traddr=0000.09.00.0 ns=1 " ; LD_PRELOAD=./spdk/build/fio/spdk_nvme  fio/fio ./spdk.fio --iodepth=256         --direct=1 --ioengine=spdk --thread=1         --time_based --runtime=$rtime         --ramp_time=5         --cpus_allowed=9         --group_reporting         	  --bs=$bz --rw=read    --output-format=json --output=/home/jason/data/ml/storage_io/Storage/_result/row_5.json &
export SPDK_FILE_NAME="trtype=PCIe  traddr=0000.7c.00.0 ns=1 " ; LD_PRELOAD=./spdk/build/fio/spdk_nvme  fio/fio ./spdk.fio --iodepth=256         --direct=1 --ioengine=spdk --thread=1         --time_based --runtime=$rtime         --ramp_time=5         --cpus_allowed=10         --group_reporting         	  --bs=$bz --rw=read    --output-format=json --output=/home/jason/data/ml/storage_io/Storage/_result/row_6.json &
export SPDK_FILE_NAME="trtype=PCIe  traddr=0000.7d.00.0 ns=1 " ; LD_PRELOAD=./spdk/build/fio/spdk_nvme  fio/fio ./spdk.fio --iodepth=256         --direct=1 --ioengine=spdk --thread=1         --time_based --runtime=$rtime         --ramp_time=5         --cpus_allowed=11         --group_reporting         	  --bs=$bz --rw=read    --output-format=json --output=/home/jason/data/ml/storage_io/Storage/_result/row_7.json &
export SPDK_FILE_NAME="trtype=PCIe  traddr=0000.7e.00.0 ns=1 " ; LD_PRELOAD=./spdk/build/fio/spdk_nvme  fio/fio ./spdk.fio --iodepth=256         --direct=1 --ioengine=spdk --thread=1         --time_based --runtime=$rtime         --ramp_time=5         --cpus_allowed=12         --group_reporting         	  --bs=$bz --rw=read    --output-format=json --output=/home/jason/data/ml/storage_io/Storage/_result/row_8.json &
export SPDK_FILE_NAME="trtype=PCIe  traddr=0000.7f.00.0 ns=1 " ; LD_PRELOAD=./spdk/build/fio/spdk_nvme  fio/fio ./spdk.fio --iodepth=256         --direct=1 --ioengine=spdk --thread=1         --time_based --runtime=$rtime         --ramp_time=5         --cpus_allowed=13         --group_reporting         	  --bs=$bz --rw=read    --output-format=json --output=/home/jason/data/ml/storage_io/Storage/_result/row_9.json &
export SPDK_FILE_NAME="trtype=PCIe  traddr=0000.a0.00.0 ns=1 " ; LD_PRELOAD=./spdk/build/fio/spdk_nvme  fio/fio ./spdk.fio --iodepth=256         --direct=1 --ioengine=spdk --thread=1         --time_based --runtime=$rtime         --ramp_time=5         --cpus_allowed=14         --group_reporting         	  --bs=$bz --rw=read    --output-format=json --output=/home/jason/data/ml/storage_io/Storage/_result/row_10.json &
export SPDK_FILE_NAME="trtype=PCIe  traddr=0000.a1.00.0 ns=1 " ; LD_PRELOAD=./spdk/build/fio/spdk_nvme  fio/fio ./spdk.fio --iodepth=256         --direct=1 --ioengine=spdk --thread=1         --time_based --runtime=$rtime         --ramp_time=5         --cpus_allowed=15         --group_reporting         	  --bs=$bz --rw=write    --output-format=json --output=/home/jason/data/ml/storage_io/Storage/_result/row_11.json &
export SPDK_FILE_NAME="trtype=PCIe  traddr=0000.a2.00.0 ns=1 " ; LD_PRELOAD=./spdk/build/fio/spdk_nvme  fio/fio ./spdk.fio --iodepth=256         --direct=1 --ioengine=spdk --thread=1         --time_based --runtime=$rtime         --ramp_time=5         --cpus_allowed=16         --group_reporting         	  --bs=$bz --rw=write    --output-format=json --output=/home/jason/data/ml/storage_io/Storage/_result/row_12.json &
export SPDK_FILE_NAME="trtype=PCIe  traddr=0000.a3.00.0 ns=1 " ; LD_PRELOAD=./spdk/build/fio/spdk_nvme  fio/fio ./spdk.fio --iodepth=256         --direct=1 --ioengine=spdk --thread=1         --time_based --runtime=$rtime         --ramp_time=5         --cpus_allowed=1         --group_reporting         	  --bs=$bz --rw=write    --output-format=json --output=/home/jason/data/ml/storage_io/Storage/_result/row_13.json &
export SPDK_FILE_NAME="trtype=PCIe  traddr=0000.c4.00.0 ns=1 " ; LD_PRELOAD=./spdk/build/fio/spdk_nvme  fio/fio ./spdk.fio --iodepth=256         --direct=1 --ioengine=spdk --thread=1         --time_based --runtime=$rtime         --ramp_time=5         --cpus_allowed=2         --group_reporting         	  --bs=$bz --rw=write    --output-format=json --output=/home/jason/data/ml/storage_io/Storage/_result/row_14.json &
export SPDK_FILE_NAME="trtype=PCIe  traddr=0000.c5.00.0 ns=1 " ; LD_PRELOAD=./spdk/build/fio/spdk_nvme  fio/fio ./spdk.fio --iodepth=256         --direct=1 --ioengine=spdk --thread=1         --time_based --runtime=$rtime         --ramp_time=5         --cpus_allowed=3         --group_reporting         	  --bs=$bz --rw=write    --output-format=json --output=/home/jason/data/ml/storage_io/Storage/_result/row_15.json &
export SPDK_FILE_NAME="trtype=PCIe  traddr=0000.c6.00.0 ns=1 " ; LD_PRELOAD=./spdk/build/fio/spdk_nvme  fio/fio ./spdk.fio --iodepth=256         --direct=1 --ioengine=spdk --thread=1         --time_based --runtime=$rtime         --ramp_time=5         --cpus_allowed=4         --group_reporting         	  --bs=$bz --rw=write    --output-format=json --output=/home/jason/data/ml/storage_io/Storage/_result/row_16.json &
export SPDK_FILE_NAME="trtype=PCIe  traddr=0000.c7.00.0 ns=1 " ; LD_PRELOAD=./spdk/build/fio/spdk_nvme  fio/fio ./spdk.fio --iodepth=256         --direct=1 --ioengine=spdk --thread=1         --time_based --runtime=$rtime         --ramp_time=5         --cpus_allowed=5         --group_reporting         	  --bs=$bz --rw=write    --output-format=json --output=/home/jason/data/ml/storage_io/Storage/_result/row_17.json &
